name: containerd-integration

on:
  workflow_run:
    workflows: [build]
    types:
      - completed
    branches:
      - "**"

jobs:
  containerd-integration:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout containerd repo
        uses: actions/checkout@v4
        with:
          repository: containerd/containerd
          ref: v1.7.24
          submodules: true

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.5"

      - name: download anocir artifact
        uses: actions/download-artifact@v4
        with:
          name: anocir
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: install anocir
        run: |
          chmod 755 ./anocir

      - name: build containerd
        run: |
          make binaries && sudo make install

      - name: link anocir
        run: |
          sudo ln -sf ${{ github.workspace }}/anocir $(which runc)

      - name: run containerd tests
        run: |
          sudo RUNC_FLAVOR=anocir make TESTFLAGS="-test.v -timeout 45m" integration
